// Generated by gencpp from file dobot/object.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_OBJECT_H
#define DOBOT_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct object_
{
  typedef object_<ContainerAllocator> Type;

  object_()
    : name()
    , x(0)
    , y(0)  {
    }
  object_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::dobot::object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::object_<ContainerAllocator> const> ConstPtr;

}; // struct object_

typedef ::dobot::object_<std::allocator<void> > object;

typedef boost::shared_ptr< ::dobot::object > objectPtr;
typedef boost::shared_ptr< ::dobot::object const> objectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot::object_<ContainerAllocator1> & lhs, const ::dobot::object_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot::object_<ContainerAllocator1> & lhs, const ::dobot::object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot::object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51440d59a83e677184abc7a885de8833";
  }

  static const char* value(const ::dobot::object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51440d59a83e6771ULL;
  static const uint64_t static_value2 = 0x84abc7a885de8833ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/object";
  }

  static const char* value(const ::dobot::object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int32 x\n"
"int32 y\n"
;
  }

  static const char* value(const ::dobot::object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::object_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_OBJECT_H
